### ISSUE TITLE
Enhance error handling

### ISSUE THREAD

**Issue by pbek** [digital-blueprint/relay-blob-library#40]
The Error class that is currently used for the Blob Backend API (Blob Library) is more or less a clone of ApiError (but without the HttpException parent class). This means the API user needs to know the internal JSON schema of the Error class to get the error properties out of the Error::getMessage(), which is not intuitive, error-prone, and needs extra documentation.

## Todo

- [x] Rename and move Helpers/Error to Api/BlobApiError (or the like)
- [x] create a constructor accepting a message string, an errorCode string and an errorDetails  array, which calls the parent (\Exception) constructor
- [x] drop the JSON encoding of the error data in the exception's message and you use normal member varibles for errorCode and errorDetails
- [x] create getters for errorCode and errorDetails
- [x] move Error::decodeErrorId to the BlobApi, make it private and rename it to something like BlogApi::getErrorIdFromApiError
- [x] create public constants in the BlobApiError for all errorIds currently used with Error (e.g. 'blob-library:delete-file-timeout' -> BlobApiError::DELETE_FILE_TIMEOUT_ERROR_ID) and pass them to the constructor of BlogApiError instead of the string literals
- [x] adapt the whole library and all tests and examples to use BlobApiError with the new methods
- [x] Create missing tests and error code documentation for `\Dbp\Relay\BlobLibrary\Api\BlobApi::putFileByIdentifier`
    - [x] Documentation
    - [x] Tests
- [x] adapt all current usages of BlobApi in Dispatch
